export const UserConstant = {
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

    GET_EMAIL_REQUEST: 'GET_EMAIL_REQUEST',
    GET_EMAIL_SUCCESS: 'GET_EMAIL_SUCCESS',
    GET_EMAIL_FAILURE: 'GET_EMAIL_FAILURE',

    CHECK_OTP_REQUEST: 'CHECK_OTP_REQUEST',
    CHECK_OTP_SUCCESS: 'CHECK_OTP_SUCCESS',
    CHECK_OTP_FAILURE: 'CHECK_OTP_FAILURE',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

    SAVE_EMAIL_USER: 'SAVE_EMAIL_USER',
    CLEAR_USER_STATE: 'CLEAR_USER_STATE',
}